### PR TITLE
Introduce CK8s package approach

### PR DESCRIPTION
**Pull request by aczajkowski**
Add new command allowing to snapshot:
- ck8s components 
- ck8s resources
- and concord.yml for all defined clusters
```
ck8s package --dest-file /tmp/package.zip
```
and then run flows using this package, which might be versioned and re-used for older clusters handling
```
ck8s -c ci -f show -p ci --package /tmp/package.zip
```
Same for starting test with older versions
```
ck8s -c ci -f runAdipOnboardingItsLocally -p ci --package /tmp/package.zip --withTests -v localItsPrefix=ex-test
```

### CODE REVIEW

**Review by ppalucha — APPROVED** [review]

**Comment by brig** [comment]
As for me, I wouldn't bundle the concord.yaml for each cluster in the package. 
If I want to add a new cluster, I have to find proper cks8-ext branch (with our latest release, obviously, it won't be the main branch), add cluster config to this branch then rebuild the entire package.

I imagined it like this:
- all configurations live separately
- `ck8s/ck8s-ext` as a separate entity
- we have some registry with configuration for customer, `ck8/ck8s-ext` version, aetion-components version and so on...

`ck8s/ck8s-ext` would be like a big Helm chart with its own lifecycle, and configurations would be the values for it, with their own lifecycle. 

so if I want to install something to the new cluster I just need to put configuration to the configuration, then find latest version (latest package) of `ck8s/ck8s-ext` and execute some flows from this package with my configuration.

if I want to update cluster with new features (we have new version of `ck8s/ck8s-ext`) then I just need to find latest version of `ck8s/ck8s-ext` and execute it.

**Comment by ppalucha** [comment]
> `ck8s/ck8s-ext` would be like a big Helm chart with its own lifecycle, and configurations would be the values for it, with their own lifecycle.

But there are dependencies between clusters configs and the flows. I imagine that in most cases we just want to have a "complete release", with both flows and cluster.yamls.
I don't think if we want to optimize for the case like running old version on new cluster. If this is really needed, it should be simple to cat the branch at the proper commit, add/modify config, create a package and so on.

**Comment by aczajkowski** [comment]
@brig 
My thinking is that:
- in the end `ck8s-ext` repository keeps track of all possible clusters that it provisions (so it's kinda it's part)
- clusterRequest defined in root `concord.yml` (which we have many in single ck8s-ext ) is tightly coupled with specific version of `ck8s` and `ck8s-ext`
- effective specific `concord.yml` cluster yaml is also tightly couple on `ck8s-cli` rendering mechanism (yaml merge)

So we have 3 things we need to track:
- ck8s revision
- ck8s-ext revision
- ck8s-cli - if rendering mechanism is compatible.

Creating single package skips all of those problems as it freezes all those things under single version-able package.

So we could either create multiple packages per-cluster - which I don't like at all, or create single package with all clusters that are defined by ck8s-ext and assure ck8s-cli will use one.

This allows to avoid re-rendering each time

P.S.
Let's merge it if you don't see any problematic issues with compatibility and running from package.
If this will show to be to complicated or heavy we can always change adjust packaging 
or add support for additional flag in future.
e.g
```ck8s -c ci package --dest-file /tmp/package.zip```
Which will render single cluster if this flag is passed.

**Comment by brig** [comment]
@ppalucha  @aczajkowski I'm not saying that we do not need this package. I'm just saing that we do not need this configs in it:)

It all depends on how we plan to use all of this. do we have an understanding of how the deployment process will look for a new client?

I see it like this:
- prepare the configurations for the new client (put it to the ck8s-ext or any other place), 
- take the latest/blessed ck8s-tools package (ck8s + ck8s-ext + ck8s-cli), 
- install everything for the client. 
as a result, we can see which version of ck8s-tools the client is using, and then update as needed. 

with single package approach we will get tons of package versions and I do not understand how we will figure out what we need to update on client side.

**Comment by aczajkowski** [comment]
> @ppalucha @aczajkowski I'm not saying that we do not need this package. I'm just saing that we do not need this configs in it:)

So you are saying about `concord.yml` ? If yes then I'm not sure how we can safely skip it.
As they are dependent on:
- included concord dependencies
- way how this file is rendered by ck8s-cli
- tightly couples clusterRequest with specific version of ck8s and ck8s-ext flows.

> with single package approach we will get tons of package versions and I do not understand how we will figure out what we need to update on client side.

Thats true :) but we can clean them up if they are not used in any cluster.
As for upgrading client (from v1 to v12) is always a problem. We will need to learn how to do it.
But for sure we need something to be able to safely operate on client cluster. So this package version was used to provision cluster with this clusterRequest object. 

So to follow on your example of development process.
For development PR's:
- we issue PR
- automation builds package locally
- automation uses package to run ITS'
- once ready it's merged
- automation builds package locally on master
- automation uses package to run ITS'  on master
- automation publishes package  on master

For handling new customers:
- we issue PR adding new customer definition
- automation builds package locally
- automation uses package to run ITS'
- Developer tries to provision customer cluster
- iterates until successful
- once ready merge PR
- automation builds package locally on master
- automation uses package to run ITS'  on master
- automation publishes package  on master and tags commit with it's version

If we need to fix older version of customer (if it was not updated)
- we cut out branches e.g. `customers/cust_name` basing on revision with which package was created
- we create PR to this branch with fixes, modifications pinted to merge to `customers/cust_name`
- from here same as for development PR's but PR's but on customer branches.

CC: @ppalucha can maybe add some ideas here. He is more fluent with it.

**Comment by aczajkowski** [comment]
@brig So my proposition would be to add some metadata files inside package describing what kind of package is this.
Then we might have 3 kinds:
- full - as it's now
- single-cluster - where it would be as now but will have single concord.yaml inside
- resources - which will have resources and flows packed only 
That should be an easy follow up

Or just have a customeextension :) like:
-  *.ck8s.zip for single cluster
- *.ck8sf.zip for full
- *.ck8sr.zip for resources only

**Comment by ppalucha** [comment]
@brig 

> with single package approach we will get tons of package versions and I do not understand how we will figure out what we need to update on client side.

With single package it's still easier to figure out what is installed at the customer side comparing to what we currently have, which is 'current master at the time of installation'.
Packaging doesn't prevent you from doing any custom stuff if needed. But it makes default operations easier and more predictable.

For example:
- You can test upgrades. If you know that client is at version X and wants to upgrade to Y, you can easily install X on your testing environment and test upgrade to Y.
- We can automate resetting your local branches to match ones from package, so it's easier to prepare hot-fixes for customer-specific version.
- For all operational actions (like onboarding a new customer etc.) we can use the exact version of package, without risk of some later changes breaking something. For example, let's say that in future version of code we remove some component and related configuration. We want to perform operation actions using the version that still supports this component.

Problem of keeping 'tons of packages' seems relatively easy. You don't need to even know how many packages you have stored somewhere in maven repo. The important bit is that you can always fetch exact package version as installed at customer's environment.

**Comment by brig** [comment]
@aczajkowski 
> So you are saying about concord.yml ? If yes then I'm not sure how we can safely skip it.

The main file is just the `clusterRequest` argument, which contains the cluster configuration. There is nothing preventing us from creating `concord.yaml` every time. So, we take the package of the required version (The package contains the required version of ck8s-components) + the cluster configuration, and then we run ck8s-cli with this data

> For handling new customers:
> we issue PR adding new customer definition
> automation builds package locally
> automation uses package to run ITS'
> Developer tries to provision customer cluster
> iterates until successful
> once ready merge PR
> automation builds package locally on master
> automation uses package to run ITS' on master
> automation publishes package on master and tags commit with it's version

In this flow, I don't see how we use this package. we only seem to be building it...

**Comment by brig** [comment]
@ppalucha 
for example client has package version X installed. I downloaded and unpacked this package. all the files in this package are mixed up. The package structure is different from what a developer usually sees (usually, all Concord files are organized by components). Now, let's say I found an error and want to fix it. How can I determine which version of ck8s/ck8s-ext I need to check out based on the package's contents?

**Comment by brig** [comment]
@ppalucha @aczajkowski 

Don't you think that all we need to do is add a dependency of `ck8s-ext` on `ck8s`? It could be just a file that specifies the version of `ck8s`, or, as @aczajkowski suggested, a `pom.xml` file that includes the `ck8s` revision.

As a result, we would have a simple relationship where the release version == tag in `ck8s-ext`, and `ck8s-ext` has a reference to `ck8s`. If I know that the client has version X installed, all I need to do is take `ck8s-ext` with the X tag.

**Comment by ppalucha** [comment]
> @ppalucha for example client has package version X installed. I downloaded and unpacked this package. all the files in this package are mixed up. The package structure is different from what a developer usually sees (usually, all Concord files are organized by components). Now, let's say I found an error and want to fix it. How can I determine which version of ck8s/ck8s-ext I need to check out based on the package's contents?

Arek proposed to have a command to reset branches to what package references to.

**Comment by ppalucha** [comment]
> @ppalucha @aczajkowski
> 
> Don't you think that all we need to do is add a dependency of `ck8s-ext` on `ck8s`? It could be just a file that specifies the version of `ck8s`, or, as @aczajkowski suggested, a `pom.xml` file that includes the `ck8s` revision.
> 
> As a result, we would have a simple relationship where the release version == tag in `ck8s-ext`, and `ck8s-ext` has a reference to `ck8s`. If I know that the client has version X installed, all I need to do is take `ck8s-ext` with the X tag.

I guess it will be almost as good. The only remaining source of differences would be how everything is assembled.
Also, if we have Java there, it would be nice to have everything built - so I still think that having a release package would be nice.

**Comment by aczajkowski** [comment]
> @ppalucha @aczajkowski
> 
> Don't you think that all we need to do is add a dependency of `ck8s-ext` on `ck8s`? It could be just a file that specifies the version of `ck8s`, or, as @aczajkowski suggested, a `pom.xml` file that includes the `ck8s` revision.
> 
> As a result, we would have a simple relationship where the release version == tag in `ck8s-ext`, and `ck8s-ext` has a reference to `ck8s`. If I know that the client has version X installed, all I need to do is take `ck8s-ext` with the X tag.

@brig @ppalucha 

This approach would still require a lot of potential error prone steps for operational use:
- checkout specific ck8s-ext tag
- run mvn build to assembly all resources (e.g.  checkout ck8s in version referenced in props)
- find out which version of cli was used (maybe it could be downloaded by mvn as dependency)
- start cli taken as dependency and point it to resources downloaded by mvn for ck8s 

All of this could be avoided when using package also we could introduce this supporting command to CLI that will reset your local resources to valid revision/commit so you can always set your local env to state from which package was created by once command.

I've also added writing metadata into package now.

**Comment by brig** [comment]
btw In this repository, there are no restrictions, and you can merge the pull request at any time :) 
I just don't quite understand how everything should work... why ck8s-cli builds the packages instead of using some release flow...

we can get everything from release flow:
- ck8s ref
- ck8s-ext ref
- ck8s-cli version
- any additional builded denendencies

**Comment by aczajkowski** [comment]
> btw In this repository, there are no restrictions, and you can merge the pull request at any time :) I just don't quite understand how everything should work... why ck8s-cli builds the packages instead of using some release flow...
> 
> we can get everything from release flow:
> 
> * ck8s ref
> * ck8s-ext ref
> * ck8s-cli version
> * any additional builded denendencies

Ok :) so let's try this approach. If this will show up to be problematic, we will move logic into release flows.
Now CLI allows to work as before without package, so we should not interfer anyone.

**Pull request merged**
